// Publish project specific data
(function() {
rh = window.rh;
model = rh.model;

rh.consts('DEFAULT_TOPIC', encodeURI("#OpMan/OpMan/Conventions_Used_In_the_User_Training1.htm".substring(1)));
rh.consts('START_FILEPATH', encodeURI('index.html'));
rh.consts('HELP_ID', '9A2BCE5F-1418-46CD-9DF7-BC77156C8CF0' || 'preview');
rh.consts('LNG_STOP_WORDS', ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "a", "after", "all", "along", "already", "also", "am", "among", "an", "and", "another", "any", "are", "at", "be", "because", "been", "between", "but", "by", "can", "do", "does", "doesn", "done", "each", "either", "for", "from", "get", "has", "have", "here", "how", "i", "if", "in", "into", "is", "isn", "it", "like", "may", "maybe", "more", "must", "need", "non", "not", "of", "ok", "okay", "on", "or", "other", "rather", "re", "s", "same", "see", "so", "some", "such", "t", "than", "that", "the", "their", "them", "then", "there", "these", "they", "this", "those", "to", "too", "unless", "use", "used", "using", "ve", "want", "was", "way", "were", "what", "when", "when", "whenever", "where", "whether", "which", "will", "with", "within", "without", "yet", "you", "your"]);
rh.consts('LNG_SUBSTR_SEARCH', 0);

model.publish(rh.consts('KEY_DIR'), "ltr");
model.publish(rh.consts('KEY_LNG'), {"Reset":"Reset","SearchResultsPerScreen":"Search results per page","SyncToc":"SyncToc","HomeButton":"Home","WebSearchButton":"WebSearch","ApplyTip":"Apply","HighlightSearchResults":"Highlight Search Results","GlossaryFilterTerms":"Filter Terms","WebSearch":"WebSearch","Show":"Show","EnableAndSearch":"Display results with all search words","ShowAll":"All","Next":"Next","Print":"Print","NoScriptErrorMsg":"Enable JavaScript support in the browser to view this page.","PreviousLabel":"Previous","Hide":"Hide","Search":"-Search-","Contents":"Contents","ShowHide":"Show/Hide","Canceled":"Canceled","EndOfResults":"End of search results.","Loading":"Loading...","SidebarToggleTip":"Expand/Collapse","ContentFilterChanged":"Content filter is changed, search again","Logo":"Logo","Logo/Author":"Powered By","JS_alert_LoadXmlFailed":"Failed to load XML file","SearchTitle":"Search","Searching":"Searching...","Disabled Next":">>","Cancel":"Cancel","JS_alert_InitDatabaseFailed":"Failed to initialize database","ResultsFoundText":"%1 result(s) found for %2","UnknownError":"Unknown error","Seperate":" |","Index":"Index","TopicsNotFound":"No results found","SearchPageTitle":"Search Results","Glossary":"Glossary","Filter":"Filter","HideAll":"Hide All","TableOfContents":"Table of Contents","NextLabel":"Next","Disabled Prev":"<<","Back":"Back","SearchOptions":"Search Options","OpenLinkInNewTab":"Open in new tab","Prev":"Previous","ToTopTip":"Go to top","NavTip":"Menu","IeCompatibilityErrorMsg":"This page cannot be viewed in Internet Explorer 8 or earlier version.","IndexFilterKewords":"Filter Keywords","JS_alert_InvalidExpression_1":"The search string you typed is not valid."});
})();